---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    servicePrincipalId: "{{ ansible_env.servicePrincipalId }}"
    spkey: "{{ ansible_env.spkey }}"
    hostSubscriptionId: "{{ ansible_env.hostSubscriptionId }}"
    tenantid: "{{ ansible_env.tenantid }}"
    resourcesgpname: "{{ ansible_env.resource_group_name }}"
  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        subscription_id: "{{ hostSubscriptionId }}"
        client_id: "{{ servicePrincipalId }}"
        tenant: "{{ tenantid }}"
        secret: "{{ spkey }}"
        name: "{{ resourcesgpname }}"
        state: absent
        force: yes    
