apiVersion: v1
kind: Service
metadata:
    name: "rsvpapp-8630"
    labels:
        app: "rsvpapp-8630"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rsvpapp-8630"